version: "2"
services:
  node:
    image: "node:10"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "7001"
    command: 
      - "npm install"
      - "npm start"
