version: '3.1'

services:
  node:
    image: "node:8.12.0"
    depends_on:
      - mysql
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "7002:7001"
    command: "npm start"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - "/home/chwech/mysql-data/egg-blog-admin:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
      - "./docker/mysql/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: admin_chwech
      MYSQL_DATABASE: wordpress
