name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # node环境
      - uses: actions/setup-node@v1
        with: 
          node-version: '8.12.0'
      - run: npm install --production

      # 打包成 tgz 文件
      # - run: tar -zcf /tmp/release.tgz .

      # 列出文件
      # - run: ls -l /tmp

      # ftp
      # - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: ${{ secrets.CHWECH_FTP_SERVER }}
      #     ftp-username: ${{ secrets.CHWECH_FTP_USERNAME }}
      #     ftp-password: ${{ secrets.CHWECH_FTP_PASSWORD }}
      #     local-dir: dist/
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: "/home/chwech/docker/egg-blog"

      # 连接服务器
      - name: ssh server and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/chwech/docker/egg-blog
            docker-compose up -d