name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # node环境
      - uses: actions/setup-node@v1
        with: 
          node-version: '8.12.0'
      - run: npm install --production

      # 打包成 tgz 文件
      - run: mkdir dist
      - run: tar -zcvf ./dist/release.tgz .

      # 列出文件
      - run: ls dist

      # ftp
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://207.148.124.80:21/chwech-ftp/egg-blog-admin
          ftp-username: chwech-ftp
          ftp-password: ${{ secrets.CHWECH_FTP }}
          local-dir: dist/
          

      # 连接服务器
      - name: ssh server and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/chwech-ftp/chwech-ftp/egg-blog-admin
            ls
            tar -zxvf release.tgz
            npm start